formatchannels:
  - defaults
dependencies:
  - arrow-cpp=17.0.0=h33d5241_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=24.3.0=py312haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.11.212=h6a15179_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py312h4b0e54e_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2024.12.31=haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - debugpy=1.8.11=py312h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h8ddb27b_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py312haa95532_0
  - ipython=8.30.0=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jsonschema=4.23.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.11.1=haff574d_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.62.2=hf25190f_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=h4364b78_2
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - numexpr=2.10.1=py312h4cd664f_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openssl=3.0.15=h827c3e9_0
  - orc=2.0.1=hd8d391b_0
  - packaging=24.2=py312haa95532_0
  - pandas=2.2.3=py312h5da7b33_0
  - parso=0.8.4=py312haa95532_0
  - pip=24.2=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - plotly=5.24.1=py312hfc267ef_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=17.0.0=py312h0158946_0
  - pygments=2.15.1=py312haa95532_1
  - python=3.12.8=h14ffc60_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=308=py312h5da7b33_0
  - pyzmq=26.2.0=py312h5da7b33_0
  - re2=2022.04.01=hd77b12b_0
  - referencing=0.30.2=py312haa95532_0
  - rpds-py=0.22.3=py312h636fa0f_0
  - setuptools=75.1.0=py312haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=9.0.0=py312haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - tzdata=2024b=h04d1e81_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
prefix: C:\Users\AdamMorse\anaconda3\envs\m5_bess_env
